### PR TITLE
chore(doc): add links to API mapping matrix

### PR DESCRIPTION
**Pull request by JordanForeman**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

---

Adding links to the API mapping matrix on the migration guide. This should (hopefully) ease the burden of locating documentation for a specific API as teams take on migrating.

### CODE REVIEW

**Comment by JordanForeman** [comment]
🦗

**Comment by mentiaa** [comment]
Thank you for your pull request. A member of the team will review it and will provide updates here about progress.

**Review by mentiaa — COMMENTED** [review]
Thank you for these edits! Could you please change the links to MWS documentation from http to https?

**Comment by JordanForeman** [comment]
@mentiaa wow. Not sure how I missed that. Thanks for the follow-up! Done b36d7b4

**Comment by mentiaa** [comment]
Thank you for your contribution!

**Pull request merged**
