### PR TITLE
Adding Invoice upload feed type

### PR DESCRIPTION
**Pull request by fernlop**
The Feed Type UPLOAD_VAT_INVOICE was added to the feed types and a guide was created, including examples for NodeJs.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mentiaa** [comment]
Thank you for your pull request. A member of the team will review it and will provide updates here about progress.

**Comment by mentiaa** [comment]
Thank you for your contribution. We have submitted your edits to the appropriate team.

Thanks,
Abby Menting
Selling Partner API Documentation

**Comment by diegocvazquez** [comment]
@mentiaa @fernlop 
Hi there
I have created a support case about uploading invoices the response was: "Please refer to the official MWS and SP-API documentation to check the up-to-date information, VAT invoice Uploading is not a valid feedtype, currently neither MWS API nor SP API support VAT invoice uploading:"
Is this funciontionallity active or not? do I need a special developer profile to use it ? I am getting 403 forbiden  when I try to create the feed (this is the 3rd step in fernlop's guide.
thanks

**Comment by fernlop** [comment]
@mentiaa 
My pull request is very old and not compatible with the current structure of the documentations. 
Should I create a new pull request for this part of the documentation or will you include my work manually?

**Pull request closed without merging**
